bestbuy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('item/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import index, about, contact, signup
from .forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view( template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

dashboard/urls.py
from django.urls import path

from .views import index

app_name = 'dashboard'

urlpatterns = [
    path('',index, name='index'),
]

item/urls.py
from django.urls import path
from .views import detail, new_item, delete, edit

app_name = 'item'


urlpatterns = [
    path('<int:pk>/', detail, name='detail'),
    path('<int:pk>/edit', edit, name='edit'),
    path('<int:pk>/delete', delete, name='delete'),
    path('new/', new_item, name='new'),
]

core/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    
    class META:
        verbose_plural_name = 'Categories'
    
    def __str__(self):
        return self.name
    
class Item(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    price = models.FloatField()
    created_on = models.DateTimeField(auto_now_add=True)
    is_sold = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.forms import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'enter your username',
        'class':'w-full px-6 py-4 rounded-xl'
    }))
    
    password = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'enter your password',
        'class':'w-full px-6 py-4 rounded-xl'
    }))

class SignUpForm(UserCreationForm):
    model = User
    fields = [
        'username',
        'email',
        'password1',
        'password2',
    ]
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'enter your username',
        'class':'w-full px-6 py-4 rounded-xl'
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder':'enter your email',
        'class':'w-full px-6 py-4 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'enter your password',
        'class':'w-full px-6 py-4 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Repeat your password',
        'class':'w-full px-6 py-4 rounded-xl'
    }))

item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 border rounded-xl'
class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'name',
            'category',
            'price',
            'description',
            'image',
        ]
        widgets={
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }
        
        
class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'name',
            'price',
            'description',
            'image',
            'is_sold'
        ]
        widgets= {
            'name':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
            'price':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
            'description':forms.Textarea(attrs={
                'class':INPUT_CLASSES
            }),
            'image':forms.FileInput(attrs={
                'class':INPUT_CLASSES
            }),
        }

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignUpForm
# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    context = {
        'items':items,
        'categories':categories
    }
    return render(request, 'core/index.html', context)


#view to the about page

def about(request):
    return render(request, 'core/about.html')


# view to the contact page

def contact(request):
    return render(request, 'core/contact.html')

#creating a signup form

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignUpForm()

    return render(request, 'core/signup.html', {'form':form})

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from item.models import Item

# Create your views here.
@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)
    
    context = {
        'items':items
    }
    return render(request, 'dashboard/index.html', context)

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required


from .models import Item
from .forms import NewItemForm, EditItemForm

# Create your views here.
# creating a detail view for each ietm listed on the home page

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    context = {
        'item':item,
        'related_items':related_items,
    }
    return render(request, 'item/detail.html', context)


# adding a new item using a form 
@login_required
def new_item(request):
    if request.method =='POST':
        form = NewItemForm(request.POST, request.FILES)
        
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()
    context = {
            'form':form,
            'title':'New Item'
        }
    return render(request, 'item/new.html', context)
        
        
#editing an item in the dashboard

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, created_by=request.user, pk=pk)
    if request.method =='POST':
        form = EditItemForm(request.POST, request.FILES,instance=item)
        
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)
    context = {
            'form':form,
            'title':'Edit Item'
        }
    return render(request, 'item/new.html', context)

#  deleting an item from a page use
@login_required
def delete(request, pk):
    item = get_object_or_404(Item, created_by=request.user, pk=pk)
    item.delete()
    
    return redirect('dashboard:index')

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %} About  BestBuy {% endblock %}

{% block content %}
<div class="px-6 py-6" >
    <h2> This is the About page</h2>
</div>
{% endblock  %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title> {% block title %}  {% endblock %}| Best Buy </title>
</head>
<body>
    {% include 'core/header.html' %}
    <div>
        {% block content %}
        {% endblock %}
    </div>
    {% include 'core/footer.html' %}
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact BestBuy {% endblock %}

{% block content %}
<div class="px-6 py-6" >
    <h2> This is the contact page</h2>
</div>
{% endblock  %}

core/templates/core/footer.html
<footer class="bg-gray-800 flex justify-between">
    <div class="w-2/3 text-white py-6 px-6" >
        <h2 class="text-2xl ">
             About Us 
        </h2>
        <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, illum provident beatae tempore recusandae omnis voluptatibus voluptas explicabo itaque nihil dolorem aliquam reiciendis ex repellat eius. Illo obcaecati debitis ut. </p>
    </div>
    <div class="w-1/3 py-6 px-6" >
        <h2 class="text-2xl text-white"> menu </h2>
        <ul>
            <li>
                <a href="{% url 'about' %}" class="text-lg text-teal-500 hover:text-teal-700">About</a>
            </li>
            <li>
                <a href="{% url 'contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a>
            </li>
            <li>
                <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a>
            </li>
            <li>
                <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of Use</a>
            </li>
        </ul>
    </div>
</footer>

core/templates/core/header.html
<nav class="flex justify-between items-center border-b border-gray-200" >
    <a href="{% url 'index' %}" class="text-2xl px-6 py-6 font-semibold">Bestbuy</a>
    <div class="space-x-6  px-6" >
        <a href="{% url 'item:new' %}" class="text-lg text-semibold">New Item</a>
        <a href="#" class="text-lg text-semibold">Browse</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'dashboard:index' %}" class="text-lg text-semibold py-3 px-6 bg-teal-500 text-white rounded-lg">Dashboard</a>
            <a href="#" class="text-lg text-semibold py-3 px-6 bg-gray-500 text-white rounded-lg">InBox </a>
        {% else %}
        <a href="{% url 'signup' %}" class="text-lg text-semibold py-3 px-6 bg-teal-500 text-white rounded-lg">Sign Up</a>
        <a href="{% url 'login' %}" class="text-lg text-semibold py-3 px-6 bg-gray-500 text-white rounded-lg">Log in</a>
        {% endif %}
    </div>
</nav>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome to BestBuy {% endblock %}

{% block content %}
<div class="px-6 py-6 mt-6 bg-gray-200 border rounded-lg">
    <h2 class="text-center text-2xl text-gray-500 " > Newest Items</h2>
    <div class="grid grid-cols-3 gap-3 py-6" >
        {% for item in items %}
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <div >
                        <img src="{{item.image.url}}" class="rounded-t-lg w-250px">
                    </div>
                    <h1 class=" text-gray-600 text-2xl font-bold py-2"> {{item.name}} </h1>
                    <p class="text-gray-400 " > {{item.created_by}} </p>
                </div>
            </a>
        {% endfor %}
    </div>
    <div class="mt-6 bg-gray-200 ">
        <h1 class="text-2xl text-center text-gray-500" >Categories</h1>
        <div class="grid grid-cols-3 gap-3 mt-2" >
            {% for category in categories %}
            <div  >
                <a href="#">
                    <div class="bg-white text-gray-400 rounded-lg" >
                        <h2 class="text-2xl"> {{category.name}} </h2>
                        <p class="text-gray-400" > {{category.items.count}}  items</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock  %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %} Sign Up {% endblock %}
 
{% block content%}
<div class=" w-1/2 bg-gray-500 my-6 p-6 text-lg mx-auto rounded-xl" >
    <h1 class="text-2xl text-white p-6" >Sign Up</h1>
    <form method="post" action="." >
        {% csrf_token %}
        <div class="mb-3"  >
            <label class="inline-block mb-2"> Username </label>
            {{form.username}}
        </div>
        <div class="mb-3"  >
            <label class="inline-block mb-2"> Choose Password </label>
            {{form.password}}
        </div>
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-500 text-white  rounded-xl" >
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
                {{form.non_field_errors}}
            </div>
        {% endif %}
        <button class="bg-teal-600 py-4 px-8 text-white font-semibold rounded-xl" >Sign Up</button>
    </form>
</div>
{% endblock%}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Sign Up {% endblock %}
 
{% block content%}
<div class=" w-1/2 bg-gray-500 my-6 p-6 text-lg mx-auto rounded-xl" >
    <h1 class="text-2xl text-white p-6" >Sign Up</h1>
    <form method="post" action="." >
        {% csrf_token %}
        <div class="mb-3"  >
            <label class="inline-block mb-2"> Username </label>
            {{form.username}}
        </div>
        <div class="mb-3"  >
            <label class="inline-block mb-2"> Email </label>
            {{form.email}}
        </div>
        <div class="mb-3"  >
            <label class="inline-block mb-2"> Choose Password </label>
            {{form.password1}}
        </div>
        <div class="mb-3"  >
            <label class="inline-block mb-2"> Repeat Password </label>
            {{form.password2}}
        </div>
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-500 text-white  rounded-xl" >
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
                {{form.non_field_errors}}
            </div>
        {% endif %}
        <button class="bg-teal-600 py-4 px-8 text-white font-semibold rounded-xl" >Sign Up</button>
    </form>
</div>
{% endblock%}

dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %}

{% block title %} Dashboard {% endblock %}

{% block content %}
<div class="px-6 py-6 mt-6 bg-gray-200 border rounded-lg">
    <h2 class="text-center text-2xl text-gray-500 " > My Items</h2>
    <div class="grid grid-cols-3 gap-3 py-6" >
        {% for item in items %}
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <div >
                        <img src="{{item.image.url}}" class="rounded-t-lg w-250px">
                    </div>
                    <h1 class=" text-gray-600 text-2xl font-bold py-2"> {{item.name}} </h1>
                    <p class="text-gray-400 " > {{item.created_by}} </p>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block content %}
<div class="grid grid-cols-5 gap-6" >
    <div class="px-4 col-span-3 py-6" >
        <img src="{{item.image.url}}" class="rounded-lg">
    </div>
    <div class="bg-gray-200 rounded-lg col-span-2 py-6 px-4 my-4 mx-2" >
        <h1 class="text-2xl mb-4" > {{item.name}} </h1>
        <p class="text-gray-600"> <strong> Price: </strong> {{item.price}}  </p>
        <p class="text-gray-600"> <strong> Seller: </strong> {{item.created_by}}  </p>
        {% if item.description %}
        <p class="text-gray-700" > <strong> Description: </strong> <br> {{item.description}} </p> <br>
        {% endif %} 
        {% if request.user == item.created_by %}
         <div class="bg-white py-4 px-6 " >
            <p class="px-2"> This is your item</p> <br>
            <a href="{%url 'item:edit' item.id %}" class="bg-teal-500 py-4 px-8 inline-block rounded-lg text-lg text-white text-semibold">Edit</a>
            <a href="{% url 'item:delete' item.id %}" class="bg-red-500 py-4 px-8 inline-block rounded-lg text-lg text-white text-semibold">Delete</a>
         </div>
        {% else %}
            <a href="#" class="py-3 px-6 bg-teal-700 text-white font-bold rounded-lg">Contact Seller</a>
        {% endif %}
    </div>
</div>
<div class="px-6 py-6 mt-6 bg-gray-200 border rounded-lg">
    <h2 class="text-center text-2xl text-gray-500 " > Related Items</h2>
    <div class="grid grid-cols-3 gap-3 py-6" >
        {% for item in related_items %}
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <div >
                        <img src="{{item.image.url}}" class="rounded-t-lg w-250px">
                    </div>
                    <h1 class=" text-gray-600 text-2xl font-bold py-2"> {{item.name}} </h1>
                    <p class="text-gray-400 " > {{item.created_by}} </p>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

item/templates/item/new.html
{% extends 'core/base.html' %}

{% block title %} {{title}}  {% endblock %}


{% block content %}
    <div class="bg-gray-200 ">
            <h1 class="mb-6"> {{title}} </h1>
        <form method="post" action="." enctype="multipart/form-data" >
            {% csrf_token %}
            <div class="space-y-2" >
                {{form.as_p}}
            </div>

            {% if form.errors or form.non_field_errors %} 
            <div class="py-3 px-6 bg-red-500" >
                {% for field in form %}
                {{field.errors}}
                {% endfor %}
                {{form.non_field_errors }}
            </div>
            {%endif %}
            <button class="bg-teal-800 py-4 px-8 text-white rounded-lg hover:bg-teal-500" >Submit</button>
        </form>
    </div>
{% endblock %}